spring.application.name=cloudheap

spring.datasource.url=jdbc:h2:mem:CloudHeap
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=talha11bu
spring.datasource.password=pass@talha11bu.CloudHeap
spring.h2.console.enabled=true
spring.h2.console.path=/console